[profile.default]
solc_version = '0.8.22'
src = 'contracts'
out = 'poc/out'
test = 'poc'
cache_path = 'cache/foundry'
optimizer = true
optimizer_runs = 200
evm_version = 'paris'

libs = [
    'node_modules/@layerzerolabs/toolbox-foundry/lib',
    'node_modules'
]

remappings = [
    'ds-test/=node_modules/@layerzerolabs/toolbox-foundry/lib/forge-std/lib/ds-test/src/',
    'forge-std/=node_modules/@layerzerolabs/toolbox-foundry/lib/forge-std/src/',
    '@openzeppelin/contracts/=node_modules/@layerzerolabs/toolbox-foundry/lib/openzeppelin-contracts/contracts/',
    '@openzeppelin/contracts-upgradeable/=node_modules/@layerzerolabs/toolbox-foundry/lib/openzeppelin-contracts-upgradeable/contracts/',
    #'@layerzerolabs/oft-evm/contracts/Fee.sol=poc/mocks/Fee.sol',
    '@layerzerolabs/oft-evm/contracts/=node_modules/@layerzerolabs/toolbox-foundry/lib/LayerZero-v2/packages/layerzero-v2/evm/oapp/contracts/oft/',
    '@layerzerolabs/oapp-evm/contracts/=node_modules/@layerzerolabs/toolbox-foundry/lib/LayerZero-v2/packages/layerzero-v2/evm/oapp/contracts/',
    '@layerzerolabs/lz-evm-protocol-v2/contracts/=node_modules/@layerzerolabs/toolbox-foundry/lib/LayerZero-v2/packages/layerzero-v2/evm/protocol/contracts/',
    '@layerzerolabs/lz-evm-messagelib-v2/contracts/=node_modules/@layerzerolabs/toolbox-foundry/lib/LayerZero-v2/packages/layerzero-v2/evm/messagelib/contracts/',
    '@layerzerolabs/toolbox-foundry/contracts/TestHelperOz5.sol=poc/mocks/TestHelperOz5.sol',
    'solidity-bytes-utils/=node_modules/@layerzerolabs/toolbox-foundry/lib/solidity-bytes-utils/',
]
